# Generated by Django 2.1.7 on 2019-07-11 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0003_auto_20190218_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNID',
            field=models.CharField(max_length=64, verbose_name='TXN ID'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_payment_paytm', to=settings.AUTH_USER_MODEL),
        ),
    ]
